version: '3.1'

services:
  postgres:
    image: postgres:14.2
    restart: always
    networks:
      - db-tier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      POSTGRES_DB: example
  web:
    build: ./web
    restart: always
    volumes:
      - ./web:/app
  server:
    build: ./server
    restart: always
    networks:
      - db-tier
      - back-tier
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/example
    depends_on:
      - postgres
    volumes:
      - ./server:/server
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./web/dist:/var/www/html
    networks:
      - back-tier
    ports:
      - 8080:80
    depends_on:
      - server
networks:
  back-tier:
  db-tier:
